export const ROUTES = {
    HOME: "/",
    FEED: "/feed",
    EDITOR: "/editor",
    DOCUMENT: "/document",
    DOCUMENT_CREATE: "/document/create",
    DOCUMENT_PARALLEL: "/document_par",
    PROFILE: "/profile",
    DOCUMENTS: "/documents",
    CONTACTS: "/contacts",
    ADMIN: "/admin",
    ADMIN_FEED: "/admin/feed",
    ADMIN_CONTACTS: "/admin/contacts",
    ADMIN_DOCUMENTS: "/admin/documents",
    ADMIN_ADAPTATION: "/admin/adaptation",
    NOT_FOUND: "/not_found",
};

export const PAGE_TITLES: Record<string, string> = {
    [ROUTES.HOME]: "Лента",
    [ROUTES.FEED]: "Лента",
    [ROUTES.EDITOR]: "Редактор",
    [ROUTES.DOCUMENT]: "Документ",
    [ROUTES.DOCUMENT_CREATE]: "Создание документа",
    [ROUTES.DOCUMENT_PARALLEL]: "Документ (параллельный)",
    [ROUTES.PROFILE]: "Профиль",
    [ROUTES.DOCUMENTS]: "Документы",
    [ROUTES.CONTACTS]: "Адресная книга",
    [ROUTES.ADMIN]: "Администрирование",
    [ROUTES.ADMIN_FEED]: "Администрирование • Лента",
    [ROUTES.ADMIN_CONTACTS]: "Администрирование • Адресная книга",
    [ROUTES.ADMIN_DOCUMENTS]: "Администрирование • Документы",
    [ROUTES.ADMIN_ADAPTATION]: "Администрирование • Адаптация",
    [ROUTES.NOT_FOUND]: "Страница не найдена",
};
